services:
  - type: web
    name: pharma-main
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist -l 3000
    staticPublishPath: ./dist
