services:
  - type: web
    name: pharma-main
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
